# -*- coding: utf-8 -*-
"""Arange_function.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rhaXYjBby_S0CFBm5DsioMQx4T8s_sPS
"""

# First import the required python libraries
import numpy as np
from skimage.io import imshow
import matplotlib.pyplot as plt
from skimage import img_as_uint
from skimage.io import imread
from skimage.color import rgb2hsv, rgb2gray

array_1 = np.array([[255,0],[0,255]])
imshow(array_1, cmap='gray')
plt.show()

array_2 = np.array([[255,0,255],[0,255,0],[255,0,255],])
plt.imshow(array_2, cmap='gray')
plt.show()

array_spectrum = np.array([np.arange(0, 255, 17),
                           np.arange(0, 255, 17),
                           np.arange(0, 255, 17),
                           np.arange(0, 255, 17)])

fig, ax = plt.subplots(1, 2, figsize=(12, 4))

ax[0].imshow(array_spectrum, cmap='gray')
ax[0].set_title('Arange_Function')

ax[1].imshow(array_spectrum.T, cmap='gray')
ax[1].set_title('Transpose_Function')

plt.show()

array_colors=np.array([[[255,0,0],[0,255,0],[0,0,255]]])
plt.imshow(array_colors)
plt.show()

dog=imread('dog.jpg')
imshow(dog)
dog.shape